Update qad_textwindow.py
Changed line 337 from

```
      editHeight = self.edit.getOptimalHeight()
```

to

```
      editHeight = int(self.edit.getOptimalHeight())
```

I was getting the following error:

```
An error has occurred while executing Python code: 

TypeError: arguments did not match any overloaded call:   resize(self, a0: QSize): argument 1 has unexpected type 'int'   resize(self, w: int, h: int): argument 2 has unexpected type 'float' 
Traceback (most recent call last):
  File "~/.local/share/QGIS/QGIS3/profiles/Preferred/python/plugins/qad/qad_textwindow.py", line 1166, in onTextChanged
    self.parentWidget().resizeEdits()
  File "~/.local/share/QGIS/QGIS3/profiles/Preferred/python/plugins/qad/qad_textwindow.py", line 348, in resizeEdits
    self.chronologyEdit.resize(w, chronologyEditHeight)
TypeError: arguments did not match any overloaded call:
  resize(self, a0: QSize): argument 1 has unexpected type 'int'
  resize(self, w: int, h: int): argument 2 has unexpected type 'float'


Python version: 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0] 
QGIS version: 3.36.2-Maidenhead Maidenhead, 6d250527200 
```

After applying the typecast to line 348, the error moved to line 351, so I back-tracked and found this.